//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    UserDal
// ObjectType:  SQL Server implementation of IUserDal (User)
// CSLAType:    EditableRoot

namespace Dal.DataAccess
{
    public partial class UserDal
    {
    }
}
