//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    UserCollDal
// ObjectType:  SQL Server implementation of IUserCollDal (UserColl)
// CSLAType:    ReadOnlyCollection

namespace Dal.DataAccess
{
    public partial class UserCollDal
    {
    }
}
