//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    UserColl
// ObjectType:  UserColl
// CSLAType:    ReadOnlyCollection

using System;
using System.Collections.Generic;
using Csla;
using CoreuiApi.Dto;
using Csla.Rules;
using CoreuiApi.Util;

namespace CoreuiApi.Lib
{

    /// <summary>
    /// UserColl (read only list).<br/>
    /// This is a generated base class of <see cref="UserColl"/> business object.
    /// This class is a root collection.
    /// </summary>
    /// <remarks>
    /// The items of the collection are <see cref="UserInfo"/> objects.
    /// </remarks>
    [Serializable]
    public partial class UserColl : ReadOnlyBindingListBase<UserColl, UserInfo>
    {

        #region Collection Business Methods

        /// <summary>
        /// Determines whether a <see cref="UserInfo"/> item is in the collection.
        /// </summary>
        /// <param name="id">The Id of the item to search for.</param>
        /// <returns><c>true</c> if the UserInfo is a collection item; otherwise, <c>false</c>.</returns>
        public bool Contains(Int64 id)
        {
            foreach (var userInfo in this)
            {
                if (userInfo.Id == id)
                {
                    return true;
                }
            }
            return false;
        }

        #endregion

        public int TotalRow { get; set; }

        #region Authoration
        protected static void AddObjectAuthorizationRules()
        {
            //auth rules
            Csla.Rules.BusinessRules.AddRule(typeof(UserColl), new Csla.Rules.CommonRules.IsInRole(AuthorizationActions.GetObject, new List<string> { Constants.UserGets }));
        }
        #endregion

        #region Factory Methods

        /// <summary>
        /// Factory method. Loads a <see cref="UserColl"/> collection.
        /// </summary>
        /// <returns>A reference to the fetched <see cref="UserColl"/> collection.</returns>
        public static UserColl GetUserColl()
        {            
            return DataPortal.Fetch<UserColl>();
        }

        public static UserColl GetUserColl(int pageIndex, int pageSize, string fullname, string user_name, string tel, string email)
        {
            return DataPortal.Fetch<UserColl>(new Criteria(pageIndex, pageSize, fullname, user_name, tel, email));
        }

        #endregion

        #region Constructor

        /// <summary>
        /// Initializes a new instance of the <see cref="UserColl"/> class.
        /// </summary>
        /// <remarks> Do not use to create a Csla object. Use factory methods instead.</remarks>
        private UserColl()
        {
            // Prevent direct creation

            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            AllowNew = false;
            AllowEdit = false;
            AllowRemove = false;
            RaiseListChangedEvents = rlce;
        }

        #endregion

        #region Criteria
        public class Criteria : CriteriaBase<Criteria>
        {
            public int PageIndex { get; set; }
            public int PageSize { get; set; }
            public string FullName { get; set; }
            public string Username { get; set; }
            public string Tel { get; set; }
            public string Email { get; set; }
            public Criteria(int pageIndex, int pageSize, string fullname, string user_name, string tel, string email)
            {
                this.PageIndex = pageIndex;
                this.PageSize = pageSize;
                this.FullName = fullname;
                this.Username = Username;
                this.Tel = tel;
                this.Email = email;
            }
        }

        #endregion

        #region Data Access

        /// <summary>
        /// Loads a <see cref="UserColl"/> collection from the database.
        /// </summary>
        protected void DataPortal_Fetch()
        {
            var args = new DataPortalHookArgs();
            OnFetchPre(args);
            using (var dalManager = DalFactoryGetManager.GetManager())
            {
                var dal = dalManager.GetProvider<IUserCollDal>();
                var data = dal.Fetch();
                Fetch(data);
            }
            OnFetchPost(args);
        }

        /// <summary>
        /// Loads a <see cref="UserColl"/> collection from the database.
        /// </summary>
        protected void DataPortal_Fetch(Criteria criteria)
        {
            var args = new DataPortalHookArgs();
            OnFetchPre(args);
            using (var dalManager = DalFactoryGetManager.GetManager())
            {
                var dal = dalManager.GetProvider<IUserCollDal>();
                int total = 0;
                var data = dal.Fetch(criteria.PageIndex, criteria.PageSize, criteria.FullName, criteria.Username, criteria.Tel, criteria.Email, ref total);
                this.TotalRow = total;
                Fetch(data);
            }
            OnFetchPost(args);
        }

        /// <summary>
        /// Loads all <see cref="UserColl"/> collection items from the given list of UserDto.
        /// </summary>
        /// <param name="data">The list of <see cref="UserDto"/>.</param>
        private void Fetch(List<UserDto> data)
        {
            IsReadOnly = false;
            var rlce = RaiseListChangedEvents;
            RaiseListChangedEvents = false;
            foreach (var dto in data)
            {
                Add(UserInfo.GetUserInfo(dto));
            }
            RaiseListChangedEvents = rlce;
            IsReadOnly = true;
        }

        #endregion

        #region Pseudo Events

        /// <summary>
        /// Occurs after setting query parameters and before the fetch operation.
        /// </summary>
        partial void OnFetchPre(DataPortalHookArgs args);

        /// <summary>
        /// Occurs after the fetch operation (object or collection is fully loaded and set up).
        /// </summary>
        partial void OnFetchPost(DataPortalHookArgs args);

        #endregion

    }
}
