//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    IUserDal
// ObjectType:  DAL interface for User
// CSLAType:    EditableRoot

using System;
using System.Collections.Generic;
using Csla;

namespace CoreuiApi.Dto
{
    /// <summary>
    /// DAL Interface for User type
    /// </summary>
    public partial interface IUserDal
    {
        /// <summary>
        /// Loads a User object from the database.
        /// </summary>
        /// <param name="id">The fetch criteria.</param>
        /// <returns>A <see cref="UserDto"/> object.</returns>
        UserDto Fetch(Int64 id);
        /// <summary>
        /// Loads a User object from the database.
        /// </summary>
        /// <param name="id">The fetch criteria.</param>
        /// <returns>A <see cref="UserDto"/> object.</returns>
        UserDto Fetch(string user_name);

        /// <summary>
        /// Inserts a new User object in the database.
        /// </summary>
        /// <param name="user">The User DTO.</param>
        /// <returns>The new <see cref="UserDto"/>.</returns>
        UserDto Insert(UserDto user);

        /// <summary>
        /// Updates in the database all changes made to the User object.
        /// </summary>
        /// <param name="user">The User DTO.</param>
        /// <returns>The updated <see cref="UserDto"/>.</returns>
        UserDto Update(UserDto user);

        /// <summary>
        /// Deletes the User object from database.
        /// </summary>
        /// <param name="id">The delete criteria.</param>
        void Delete(Int64 id);
    }
}
