//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    IUserDal
// ObjectType:  DAL interface for User
// CSLAType:    EditableRoot

namespace Dal
{
    public partial interface IUserDal
    {
    }
}
