//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    IUserCollDal
// ObjectType:  DAL interface for UserColl
// CSLAType:    ReadOnlyCollection

namespace Dal
{
    public partial interface IUserCollDal
    {
    }
}
