//  This file was generated by CSLA Object Generator - CslaGenFork v4.3.0
//
// Filename:    IUserInfoDal
// ObjectType:  DAL interface for UserInfo
// CSLAType:    ReadOnlyObject

namespace Dal
{
    public partial class UserInfoDto
    {
    }
}
